/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jpanel;

import static Jframe.mainframe.lapthedocgia_in_menu;
import static Jframe.mainframe.thongtindocgia_in_menu;

/**
 *
 * @author Admin
 */
public class DocGia_menu extends javax.swing.JPanel {

    /**
     * Creates new form DocGia_menu
     */
    public DocGia_menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LB_docgiamenu = new javax.swing.JLabel();
        BT_LapTheDocGia = new javax.swing.JButton();
        BT_ThongTinDocGia = new javax.swing.JButton();

        LB_docgiamenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/docgiamain.png"))); // NOI18N

        BT_LapTheDocGia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BT_LapTheDocGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lapthedocgia.png"))); // NOI18N
        BT_LapTheDocGia.setText("Lập Thẻ Độc Giả");
        BT_LapTheDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_LapTheDocGiaActionPerformed(evt);
            }
        });

        BT_ThongTinDocGia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BT_ThongTinDocGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/thongtindocgia.png"))); // NOI18N
        BT_ThongTinDocGia.setText("Thông Tin Độc Giả");
        BT_ThongTinDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ThongTinDocGiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LB_docgiamenu)
                .addGap(128, 128, 128)
                .addComponent(BT_LapTheDocGia)
                .addGap(197, 197, 197)
                .addComponent(BT_ThongTinDocGia)
                .addGap(0, 164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LB_docgiamenu)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BT_ThongTinDocGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BT_LapTheDocGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BT_LapTheDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_LapTheDocGiaActionPerformed
        lapthedocgia_in_menu();        // TODO add your handling code here:
    }//GEN-LAST:event_BT_LapTheDocGiaActionPerformed

    private void BT_ThongTinDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ThongTinDocGiaActionPerformed
        // TODO add your handling code here:
        thongtindocgia_in_menu();
    }//GEN-LAST:event_BT_ThongTinDocGiaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_LapTheDocGia;
    private javax.swing.JButton BT_ThongTinDocGia;
    private javax.swing.JLabel LB_docgiamenu;
    // End of variables declaration//GEN-END:variables
}
