/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jpanel;

import static Controller.login_controller.get_current_user_permission;
import static Jframe.mainframe.thaydoiquydinh_in_menu;
import static Jframe.mainframe.thongtinphienban_in_menu;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class HeThong_menu extends javax.swing.JPanel {

    /**
     * Creates new form HeThong_menu
     */
    public HeThong_menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LB_hethong_menu = new javax.swing.JLabel();
        BT_ThayDoiQuyDinh = new javax.swing.JButton();
        BT_ThongTinPhienBan = new javax.swing.JButton();

        LB_hethong_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hethongmain.png"))); // NOI18N

        BT_ThayDoiQuyDinh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BT_ThayDoiQuyDinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/thongtinphienban.png"))); // NOI18N
        BT_ThayDoiQuyDinh.setText("Thay Đổi Quy Định");
        BT_ThayDoiQuyDinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ThayDoiQuyDinhActionPerformed(evt);
            }
        });

        BT_ThongTinPhienBan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BT_ThongTinPhienBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/thongtinphienban.png"))); // NOI18N
        BT_ThongTinPhienBan.setText("Thông Tin Phiên Bản");
        BT_ThongTinPhienBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ThongTinPhienBanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LB_hethong_menu)
                .addGap(107, 107, 107)
                .addComponent(BT_ThayDoiQuyDinh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                .addComponent(BT_ThongTinPhienBan)
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LB_hethong_menu)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BT_ThongTinPhienBan, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_ThayDoiQuyDinh, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public static void thaydoiquydinh(){
        if (get_current_user_permission().equals("admin")){
                thaydoiquydinh_in_menu();
            }else{
                JOptionPane.showMessageDialog(null, "Chỉ admin được quyền truy cập!!!" ,
                  "Title", JOptionPane.WARNING_MESSAGE);
            }
    }
    private void BT_ThayDoiQuyDinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ThayDoiQuyDinhActionPerformed
            if (get_current_user_permission().equals("admin")){
                thaydoiquydinh_in_menu();
            }else{
                JOptionPane.showMessageDialog(null, "Chỉ admin được quyền truy cập!!!" ,
                  "Title", JOptionPane.WARNING_MESSAGE);
            }
                
    }//GEN-LAST:event_BT_ThayDoiQuyDinhActionPerformed

    private void BT_ThongTinPhienBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ThongTinPhienBanActionPerformed
        // TODO add your handling code here:
        thongtinphienban_in_menu();
    }//GEN-LAST:event_BT_ThongTinPhienBanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_ThayDoiQuyDinh;
    private javax.swing.JButton BT_ThongTinPhienBan;
    private javax.swing.JLabel LB_hethong_menu;
    // End of variables declaration//GEN-END:variables
}
