/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jpanel;

import static Jframe.mainframe.themsach_in_menu;
import static Jframe.mainframe.thongtinsach_in_menu;
import static Jpanel.ThongTinSach.reload_book_data_table;

/**
 *
 * @author Admin
 */
public class Sach_menu extends javax.swing.JPanel {

    /**
     * Creates new form Sach_menu
     */
    public Sach_menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LB_sachmenu = new javax.swing.JLabel();
        BT_ThemSach = new javax.swing.JButton();
        BT_ThongTinSach = new javax.swing.JButton();

        LB_sachmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/themsachmain.png"))); // NOI18N

        BT_ThemSach.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BT_ThemSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/themsach.png"))); // NOI18N
        BT_ThemSach.setText("Thêm Sách");
        BT_ThemSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ThemSachActionPerformed(evt);
            }
        });

        BT_ThongTinSach.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BT_ThongTinSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/thongtinsach.png"))); // NOI18N
        BT_ThongTinSach.setText("Thông Tin Sách");
        BT_ThongTinSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ThongTinSachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LB_sachmenu)
                .addGap(185, 185, 185)
                .addComponent(BT_ThemSach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                .addComponent(BT_ThongTinSach)
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LB_sachmenu)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BT_ThongTinSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BT_ThemSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BT_ThongTinSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ThongTinSachActionPerformed
        // TODO add your handling code here:
        thongtinsach_in_menu();
        reload_book_data_table();
    }//GEN-LAST:event_BT_ThongTinSachActionPerformed

    private void BT_ThemSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ThemSachActionPerformed
        // TODO add your handling code here:
        themsach_in_menu();
    }//GEN-LAST:event_BT_ThemSachActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_ThemSach;
    private javax.swing.JButton BT_ThongTinSach;
    private javax.swing.JLabel LB_sachmenu;
    // End of variables declaration//GEN-END:variables
}
