/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jpanel;

import static Jframe.mainframe.doimatkhau_in_menu;
import static Jframe.mainframe.thongtintaikhoan_in_menu;

/**
 *
 * @author Admin
 */
public class TaiKhoan_menu extends javax.swing.JPanel {

    /**
     * Creates new form TaiKhoan_menu
     */
    public TaiKhoan_menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LB_doimatkhau_menu = new javax.swing.JLabel();
        BT_DoiMatKhau = new javax.swing.JButton();
        BT_ThongTinTaiKhoan = new javax.swing.JButton();

        LB_doimatkhau_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/taikhoanmain.png"))); // NOI18N

        BT_DoiMatKhau.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BT_DoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doimatkhau.png"))); // NOI18N
        BT_DoiMatKhau.setText("Đổi Mật Khẩu");
        BT_DoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_DoiMatKhauActionPerformed(evt);
            }
        });

        BT_ThongTinTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BT_ThongTinTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/thongtintaikhoan.png"))); // NOI18N
        BT_ThongTinTaiKhoan.setText("Thông Tin Tài Khoản");
        BT_ThongTinTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ThongTinTaiKhoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LB_doimatkhau_menu)
                .addGap(139, 139, 139)
                .addComponent(BT_DoiMatKhau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                .addComponent(BT_ThongTinTaiKhoan)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LB_doimatkhau_menu)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_ThongTinTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_DoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BT_DoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_DoiMatKhauActionPerformed
        // TODO add your handling code here:
        doimatkhau_in_menu();
    }//GEN-LAST:event_BT_DoiMatKhauActionPerformed

    private void BT_ThongTinTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ThongTinTaiKhoanActionPerformed
        // TODO add your handling code here:
        thongtintaikhoan_in_menu();
    }//GEN-LAST:event_BT_ThongTinTaiKhoanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_DoiMatKhau;
    private javax.swing.JButton BT_ThongTinTaiKhoan;
    private javax.swing.JLabel LB_doimatkhau_menu;
    // End of variables declaration//GEN-END:variables
}
