/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jpanel;

/**
 *
 * @author Admin
 */
public class ThongTinDocGia extends javax.swing.JPanel {

    /**
     * Creates new form ThongTinDocGia
     */
    public ThongTinDocGia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LB_cachtimkiem4 = new javax.swing.JLabel();
        CB_CachTimKiem = new javax.swing.JComboBox<>();
        TF_TuTimKiem = new javax.swing.JTextField();
        LB_tutimkiem4 = new javax.swing.JLabel();
        BT_tim4 = new javax.swing.JButton();
        LB_masach = new javax.swing.JLabel();
        LB_tensach = new javax.swing.JLabel();
        LB_tacgia = new javax.swing.JLabel();
        LB_soluong = new javax.swing.JLabel();
        TF_DiaChi = new javax.swing.JTextField();
        TF_CMND = new javax.swing.JTextField();
        TF_TenDocGia = new javax.swing.JTextField();
        TF_MaDocGia = new javax.swing.JTextField();
        LB_theloai = new javax.swing.JLabel();
        LB_nxb = new javax.swing.JLabel();
        LB_namxuatban = new javax.swing.JLabel();
        LB_trigia = new javax.swing.JLabel();
        FF_Email = new javax.swing.JFormattedTextField();
        CB_LoaiDocGia = new javax.swing.JComboBox<>();
        CB_GioiTinh = new javax.swing.JComboBox<>();
        BT_GiaHan = new javax.swing.JButton();
        BT_in = new javax.swing.JButton();
        BT_sua = new javax.swing.JButton();
        BT_xoa = new javax.swing.JButton();
        BT_luu = new javax.swing.JButton();
        BT_huy = new javax.swing.JButton();
        PN_thongtinsach_ketqua = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Date_NgaySinh = new com.toedter.calendar.JDateChooser();

        LB_cachtimkiem4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LB_cachtimkiem4.setText("Cách tìm kiếm");

        CB_CachTimKiem.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        CB_CachTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã Độc Giả", "Tên độc giả", "CMND", "Ngày sinh", " " }));

        TF_TuTimKiem.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        LB_tutimkiem4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LB_tutimkiem4.setText("Từ tìm kiếm");

        BT_tim4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/thongtinsach.png"))); // NOI18N

        LB_masach.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LB_masach.setText("Mã độc giả");

        LB_tensach.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LB_tensach.setText("Tên độc giả");

        LB_tacgia.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LB_tacgia.setText("CMND");

        LB_soluong.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LB_soluong.setText("Địa chỉ");

        TF_DiaChi.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        TF_CMND.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        TF_CMND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_CMNDActionPerformed(evt);
            }
        });

        TF_TenDocGia.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        TF_TenDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_TenDocGiaActionPerformed(evt);
            }
        });

        TF_MaDocGia.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        LB_theloai.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LB_theloai.setText("giới tính");

        LB_nxb.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LB_nxb.setText("Loại độc giả");

        LB_namxuatban.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LB_namxuatban.setText("Ngày sinh");

        LB_trigia.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LB_trigia.setText("Email");

        FF_Email.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        FF_Email.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        CB_LoaiDocGia.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        CB_LoaiDocGia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vip", "Normal", "Item 3", "Item 4" }));

        CB_GioiTinh.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        CB_GioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Item 3", "Item 4" }));

        BT_GiaHan.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BT_GiaHan.setText("Gia hạn");

        BT_in.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BT_in.setText("In");

        BT_sua.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BT_sua.setText("Sửa");

        BT_xoa.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BT_xoa.setText("Xoá");

        BT_luu.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BT_luu.setText("Lưu");

        BT_huy.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BT_huy.setText("Huỷ");
        BT_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_huyActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã độc giả", "Họ và tên", "Ngày lập thẻ", "Loại độc giả", "CMND", "Ngày Sinh", "Giới tính"
            }
        ));
        PN_thongtinsach_ketqua.setViewportView(jTable1);

        Date_NgaySinh.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LB_cachtimkiem4)
                                    .addComponent(LB_tutimkiem4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CB_CachTimKiem, 0, 216, Short.MAX_VALUE)
                                    .addComponent(TF_TuTimKiem)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(BT_tim4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(137, 137, 137)
                        .addComponent(BT_GiaHan)
                        .addGap(57, 57, 57)
                        .addComponent(BT_in)
                        .addGap(55, 55, 55)
                        .addComponent(BT_sua)
                        .addGap(43, 43, 43)
                        .addComponent(BT_xoa)
                        .addGap(43, 43, 43)
                        .addComponent(BT_luu)
                        .addGap(43, 43, 43)
                        .addComponent(BT_huy))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PN_thongtinsach_ketqua)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TF_MaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LB_nxb)
                                            .addComponent(LB_theloai))
                                        .addGap(27, 27, 27))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(LB_soluong)
                                                    .addComponent(LB_tacgia))
                                                .addGap(57, 57, 57)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(TF_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(TF_CMND, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(25, 25, 25)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(LB_masach)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(LB_tensach)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(TF_TenDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LB_namxuatban)
                                            .addComponent(LB_trigia))
                                        .addGap(45, 45, 45)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(FF_Email)
                                    .addComponent(CB_LoaiDocGia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Date_NgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CB_GioiTinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LB_cachtimkiem4)
                            .addComponent(CB_CachTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LB_tensach))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LB_tutimkiem4)
                            .addComponent(TF_TuTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(BT_tim4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LB_masach)
                            .addComponent(LB_theloai)
                            .addComponent(TF_MaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CB_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LB_nxb)
                            .addComponent(CB_LoaiDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_TenDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LB_tacgia)
                                .addComponent(LB_namxuatban)
                                .addComponent(TF_CMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Date_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LB_soluong)
                            .addComponent(FF_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LB_trigia))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_in)
                    .addComponent(BT_GiaHan)
                    .addComponent(BT_sua)
                    .addComponent(BT_xoa)
                    .addComponent(BT_luu)
                    .addComponent(BT_huy))
                .addGap(18, 18, 18)
                .addComponent(PN_thongtinsach_ketqua, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TF_CMNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_CMNDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_CMNDActionPerformed

    private void BT_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_huyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_huyActionPerformed

    private void TF_TenDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_TenDocGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_TenDocGiaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_GiaHan;
    private javax.swing.JButton BT_huy;
    private javax.swing.JButton BT_in;
    private javax.swing.JButton BT_luu;
    private javax.swing.JButton BT_sua;
    private javax.swing.JButton BT_tim4;
    private javax.swing.JButton BT_xoa;
    private javax.swing.JComboBox<String> CB_CachTimKiem;
    private javax.swing.JComboBox<String> CB_GioiTinh;
    private javax.swing.JComboBox<String> CB_LoaiDocGia;
    private com.toedter.calendar.JDateChooser Date_NgaySinh;
    private javax.swing.JFormattedTextField FF_Email;
    private javax.swing.JLabel LB_cachtimkiem4;
    private javax.swing.JLabel LB_masach;
    private javax.swing.JLabel LB_namxuatban;
    private javax.swing.JLabel LB_nxb;
    private javax.swing.JLabel LB_soluong;
    private javax.swing.JLabel LB_tacgia;
    private javax.swing.JLabel LB_tensach;
    private javax.swing.JLabel LB_theloai;
    private javax.swing.JLabel LB_trigia;
    private javax.swing.JLabel LB_tutimkiem4;
    private javax.swing.JScrollPane PN_thongtinsach_ketqua;
    private javax.swing.JTextField TF_CMND;
    private javax.swing.JTextField TF_DiaChi;
    private javax.swing.JTextField TF_MaDocGia;
    private javax.swing.JTextField TF_TenDocGia;
    private javax.swing.JTextField TF_TuTimKiem;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
